version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: panda-app
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./composer.json:/var/www/composer.json
        networks:
            - app-network

    db:
        image: postgres:15
        container_name: panda-postgres
        restart: unless-stopped
        tty: true
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        volumes:
            - dbdata:/var/lib/postgresql/data
        networks:
            - app-network

    webserver:
        image: nginx:alpine
        container_name: panda-nginx
        restart: unless-stopped
        ports:
            - "8080:80"
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./:/var/www
        depends_on:
            - app
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    dbdata:
        driver: local
